[package]
name = "multiplayer-client"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
cpal = "0.16.0"
opus = "0.3.0"
iced = "0.13.1"
message-io = "0.19.0"
serde = { version = "1.0.219", features = ["derive"] }
bincode = { version = "2.0.1", features = ["serde"] }
