[workspace]
resolver = "3"
members = ["host", "client"]

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "debuginfo"

[build]
rustflags = ["-C", "target-cpu=native"]